homework 29
Alkey/Shop pull request #9
Opened 2020-09-16 16:09 UTC by Alkey

2020-09-16 19:11 UTC, frostpv commented on src/main/java/com/internet/shop/controllers/IndexController.java
> +                .create(new User("Bob", "Bob", "1", Set.of(Role.of("ADMIN"), Role.of("USER"))));
У админа только одна роль, я уже знаю это))))

2020-09-16 19:11 UTC, frostpv commented on src/main/java/com/internet/shop/web/filters/AuthorizationFilter.java
> +        if (!protectedUrls.containsKey(requestUrl)
Поспрашиваю про это условие тебя в слеке

2020-09-16 20:44 UTC, Alkey commented on src/main/java/com/internet/shop/controllers/IndexController.java
> +                .create(new User("Bob", "Bob", "1", Set.of(Role.of("ADMIN"), Role.of("USER"))));
Исправил

2020-09-17 06:34 UTC, KseniiaMakarova requested changes

2020-09-17 06:34 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/IndexController.java
>          shoppingCartService.create(new ShoppingCart(alice.getId()));
let's create a separate InjectDataController for this purpose
we should not place business logic in the init() method

2020-09-17 06:34 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filters/AuthorizationFilter.java
> +        protectedUrls.put("/order/order-products", Set.of(Role.RoleName.USER));
is this controller also available to admin from show-all-orders page?

2020-09-17 09:47 UTC, KseniiaMakarova approved these changes

2020-09-17 09:48 UTC, merged